name: Slither Analysis
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: yarn-v2-
      - run: yarn
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Clean project
        run: yarn run clean
      - uses: crytic/slither-action@v0.1.1
